version: '3'
services:
  client:
    image: sleepwalker-python
    build: ./pythonweb/
    ports:
      - "32159:5000"
    networks:
      - internal_network
      - out_network
  server:
    image: nginx:1.15
    expose:
      - "80"
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal_network
  javaweb:
    image: sleepwalker-java
    build: ./javaweb/
    expose:
      - "8080"
    networks:
      - internal_network
networks:
  internal_network:
    internal: true
    ipam:
      driver: default
  out_network:
    ipam:
      driver: default